const data = [
    {
        id: 'dashboards',
        group: 'writer',
        icon: 'iconsminds-shop-4',
        label: 'menu.dashboards',
        to: '/app/dashboards',
        subs: [],
    },
    {
        id: 'myprojects',
        group: 'writer',
        icon: 'iconsminds-air-balloon-1',
        label: 'menu.allprojects',
        to: '/app/myprojects',
        subs: [],
    },
    {
        id: 'mypayments',
        group: 'writer',
        icon: 'iconsminds-digital-drawing',
        label: 'menu.paymentsandfeedback',
        to: '/app/mypayments',
        subs: [],
    },
    {
        id: 'profile',
        group: 'writer',
        icon: 'iconsminds-profile',
        label: 'menu.edit-profile',
        to: '/app/profile',
        subs: [],
    },
    {
        id: 'dashboardsEditor',
        group: 'editor',
        icon: 'iconsminds-shop-4',
        label: 'menu.dashboards',
        to: '/app/editor-dashboards',
        subs: [],
    },
    {
        id: 'myprojectsEditor',
        group: 'editor',
        icon: 'iconsminds-air-balloon-1',
        label: 'menu.allprojects',
        to: '/app/editor-myprojects',
        subs: [],
    },
    {
        id: 'mypaymentsEditor',
        group: 'editor',
        icon: 'iconsminds-digital-drawing',
        label: 'menu.paymentsandfeedback',
        to: '/app/editor-mypayments',
        subs: [],
    },
    {
        id: 'profileEditor',
        group: 'editor',
        icon: 'iconsminds-profile',
        label: 'menu.edit-profile',
        to: '/app/editor-profile',
        subs: [],
    },
    {
        id: 'dashboardsBusiness',
        group: 'client',
        icon: 'iconsminds-shop-4',
        label: 'menu.dashboards',
        to: '/app/business-dashboards',
        subs: [],
    },
    {
        id: 'myprojectsBusiness',
        group: 'client',
        icon: 'iconsminds-air-balloon-1',
        label: 'menu.allprojects',
        to: '/app/business-myprojects',
        subs: [],
    },
    {
        id: 'mypaymentsBusiness',
        group: 'client',
        icon: 'iconsminds-digital-drawing',
        label: 'menu.paymentsandfeedback',
        to: '/app/business-mypayments',
        subs: [],
    },
    {
        id: 'profileBusiness',
        group: 'client',
        icon: 'iconsminds-profile',
        label: 'menu.edit-profile',
        to: '/app/business-profile',
        subs: [],
    },
    {
        id: 'addProject',
        group: 'client',
        icon: 'iconsminds-add-file',
        label: 'menu.add-project',
        to: '/app/myprojects/project',
        subs: [],
    },
]
export default data
